INSERT INTO bookmarks (user_category_id, bookmark_title, bookmark_url) VALUES (1, 'Github', 'http://www.github.com');
INSERT INTO bookmarks (user_category_id, bookmark_title, bookmark_url) VALUES (1, 'Stackoverflow', 'http://www.stackoverflow.com');
INSERT INTO bookmarks (user_category_id, bookmark_title, bookmark_url) VALUES (1, 'Linkedin', 'http://www.linkedin.com');
INSERT INTO bookmarks (user_category_id, bookmark_title, bookmark_url) VALUES (1, 'MDN', 'https://developer.mozilla.org/en-US/');
INSERT INTO bookmarks (user_category_id, bookmark_title, bookmark_url) VALUES (2, 'Snapchat', 'https://www.snapchat.com/');
INSERT INTO bookmarks (user_category_id, bookmark_title, bookmark_url) VALUES (2, 'Twitter', 'http://www.twitter.com');
INSERT INTO bookmarks (user_category_id, bookmark_title, bookmark_url) VALUES (2, 'Instagram', 'http://www.instagram.com');
INSERT INTO bookmarks (user_category_id, bookmark_title, bookmark_url) VALUES (2, 'Facebook', 'http://www.facebook.com');
INSERT INTO bookmarks (user_category_id, bookmark_title, bookmark_url) VALUES (3, 'Reddit', 'http://www.reddit.com');
INSERT INTO bookmarks (user_category_id, bookmark_title, bookmark_url) VALUES (3, 'Pinterest', 'http://www.pinterest.com');
INSERT INTO bookmarks (user_category_id, bookmark_title, bookmark_url) VALUES (3, 'Quora', 'http://www.quora.com');
INSERT INTO bookmarks (user_category_id, bookmark_title, bookmark_url) VALUES (3, 'Bookshare', 'https://www.bookshare.org/cms/');
INSERT INTO bookmarks (user_category_id, bookmark_title, bookmark_url) VALUES (4, 'Netflix', 'https://www.netflix.com/ca/');
INSERT INTO bookmarks (user_category_id, bookmark_title, bookmark_url) VALUES (4, 'Youtube', 'http://www.youtube.com');
INSERT INTO bookmarks (user_category_id, bookmark_title, bookmark_url) VALUES (4, 'Twitch', 'http://www.twitch.com');
INSERT INTO bookmarks (user_category_id, bookmark_title, bookmark_url) VALUES (4, 'Disney Plus', 'https://www.disneyplus.com/home');

INSERT INTO bookmarks (user_category_id, bookmark_title, bookmark_url) VALUES (5, 'Amazon', 'https://www.amazon.ca/');
INSERT INTO bookmarks (user_category_id, bookmark_title, bookmark_url) VALUES (5, 'Canada Computers', 'https://www.canadacomputers.com/');
INSERT INTO bookmarks (user_category_id, bookmark_title, bookmark_url) VALUES (5, 'Newegg', 'https://www.newegg.ca/');
INSERT INTO bookmarks (user_category_id, bookmark_title, bookmark_url) VALUES (6, 'Spotify', 'https://open.spotify.com/');
INSERT INTO bookmarks (user_category_id, bookmark_title, bookmark_url) VALUES (6, 'Youtube', 'https://www.youtube.com/');
INSERT INTO bookmarks (user_category_id, bookmark_title, bookmark_url) VALUES (6, 'Ableton', 'https://www.ableton.com/en/');
INSERT INTO bookmarks (user_category_id, bookmark_title, bookmark_url) VALUES (7, 'Chefs Pencil', 'https://www.chefspencil.com/');
INSERT INTO bookmarks (user_category_id, bookmark_title, bookmark_url) VALUES (7, 'Food Network', 'https://www.foodnetwork.com/');
INSERT INTO bookmarks (user_category_id, bookmark_title, bookmark_url) VALUES (7, 'Tasty', 'https://tasty.co/');
INSERT INTO bookmarks (user_category_id, bookmark_title, bookmark_url) VALUES (8, 'Sketchpad', 'https://sketch.io/sketchpad/');
INSERT INTO bookmarks (user_category_id, bookmark_title, bookmark_url) VALUES (8, 'Kleki', 'https://kleki.com/');
INSERT INTO bookmarks (user_category_id, bookmark_title, bookmark_url) VALUES (8, 'Auto Draw', 'https://www.autodraw.com/');